version: "3.8"
services:
  backend-api:
    container_name: backend_api
    command: uvicorn backend_api.main:app --host 0.0.0.0 --port 8005
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8005:8005'
    networks:
      - momox
    volumes:
      - ${PWD}:/backend_api
networks:
  momox:
    external: false