version: "3.8"
services:
  backend-api:
    container_name: backend-api
    command: uvicorn backend-api.main:app --host 0.0.0.0 --port 8005
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8005:8005'
    networks:
      - momox
    volumes:
      - .:/backend-api:cached
networks:
  momox:
    external: false